var annotated_dup =
[
    [ "sbepp", "namespacesbepp.html", [
      [ "detail", "namespacesbepp_1_1detail.html", [
        [ "bitset_base", "classsbepp_1_1detail_1_1bitset__base.html", "classsbepp_1_1detail_1_1bitset__base" ],
        [ "byte_range", "classsbepp_1_1detail_1_1byte__range.html", "classsbepp_1_1detail_1_1byte__range" ],
        [ "composite_base", "classsbepp_1_1detail_1_1composite__base.html", null ],
        [ "dynamic_array_ref", "classsbepp_1_1detail_1_1dynamic__array__ref.html", "classsbepp_1_1detail_1_1dynamic__array__ref" ],
        [ "entry_base", "classsbepp_1_1detail_1_1entry__base.html", "classsbepp_1_1detail_1_1entry__base" ],
        [ "flat_group_base", "classsbepp_1_1detail_1_1flat__group__base.html", "classsbepp_1_1detail_1_1flat__group__base" ],
        [ "message_base", "classsbepp_1_1detail_1_1message__base.html", null ],
        [ "nested_group_base", "classsbepp_1_1detail_1_1nested__group__base.html", "classsbepp_1_1detail_1_1nested__group__base" ],
        [ "optional_base", "classsbepp_1_1detail_1_1optional__base.html", "classsbepp_1_1detail_1_1optional__base" ],
        [ "required_base", "classsbepp_1_1detail_1_1required__base.html", "classsbepp_1_1detail_1_1required__base" ],
        [ "static_array_ref", "classsbepp_1_1detail_1_1static__array__ref.html", "classsbepp_1_1detail_1_1static__array__ref" ]
      ] ],
      [ "byte_type", "structsbepp_1_1byte__type.html", "structsbepp_1_1byte__type" ],
      [ "char_opt_t", "classsbepp_1_1char__opt__t.html", null ],
      [ "char_t", "classsbepp_1_1char__t.html", null ],
      [ "composite_traits", "classsbepp_1_1composite__traits.html", "classsbepp_1_1composite__traits" ],
      [ "cursor", "classsbepp_1_1cursor.html", "classsbepp_1_1cursor" ],
      [ "data_traits", "classsbepp_1_1data__traits.html", "classsbepp_1_1data__traits" ],
      [ "default_init_t", "structsbepp_1_1default__init__t.html", null ],
      [ "double_opt_t", "classsbepp_1_1double__opt__t.html", null ],
      [ "double_t", "classsbepp_1_1double__t.html", null ],
      [ "enum_traits", "classsbepp_1_1enum__traits.html", "classsbepp_1_1enum__traits" ],
      [ "enum_value_traits", "classsbepp_1_1enum__value__traits.html", null ],
      [ "field_traits", "classsbepp_1_1field__traits.html", "classsbepp_1_1field__traits" ],
      [ "float_opt_t", "classsbepp_1_1float__opt__t.html", null ],
      [ "float_t", "classsbepp_1_1float__t.html", null ],
      [ "group_traits", "classsbepp_1_1group__traits.html", "classsbepp_1_1group__traits" ],
      [ "int16_opt_t", "classsbepp_1_1int16__opt__t.html", null ],
      [ "int16_t", "classsbepp_1_1int16__t.html", null ],
      [ "int32_opt_t", "classsbepp_1_1int32__opt__t.html", null ],
      [ "int32_t", "classsbepp_1_1int32__t.html", null ],
      [ "int64_opt_t", "classsbepp_1_1int64__opt__t.html", null ],
      [ "int64_t", "classsbepp_1_1int64__t.html", null ],
      [ "int8_opt_t", "classsbepp_1_1int8__opt__t.html", null ],
      [ "int8_t", "classsbepp_1_1int8__t.html", null ],
      [ "is_enum", "structsbepp_1_1is__enum.html", null ],
      [ "message_traits", "classsbepp_1_1message__traits.html", "classsbepp_1_1message__traits" ],
      [ "nullopt_t", "structsbepp_1_1nullopt__t.html", null ],
      [ "schema_traits", "classsbepp_1_1schema__traits.html", "classsbepp_1_1schema__traits" ],
      [ "set_choice_traits", "classsbepp_1_1set__choice__traits.html", null ],
      [ "set_traits", "classsbepp_1_1set__traits.html", "classsbepp_1_1set__traits" ],
      [ "size_bytes_checked_result", "structsbepp_1_1size__bytes__checked__result.html", "structsbepp_1_1size__bytes__checked__result" ],
      [ "traits_tag", "structsbepp_1_1traits__tag.html", "structsbepp_1_1traits__tag" ],
      [ "type_traits", "classsbepp_1_1type__traits.html", "classsbepp_1_1type__traits" ],
      [ "uint16_opt_t", "classsbepp_1_1uint16__opt__t.html", null ],
      [ "uint16_t", "classsbepp_1_1uint16__t.html", null ],
      [ "uint32_opt_t", "classsbepp_1_1uint32__opt__t.html", null ],
      [ "uint32_t", "classsbepp_1_1uint32__t.html", null ],
      [ "uint64_opt_t", "classsbepp_1_1uint64__opt__t.html", null ],
      [ "uint64_t", "classsbepp_1_1uint64__t.html", null ],
      [ "uint8_opt_t", "classsbepp_1_1uint8__opt__t.html", null ],
      [ "uint8_t", "classsbepp_1_1uint8__t.html", null ],
      [ "unknown_enum_value_tag", "structsbepp_1_1unknown__enum__value__tag.html", null ]
    ] ]
];